Vagrant.configure("2") do |config|
    config.vm.define "devBox_droplet" do |node|
    node.vm.host_name = "devBox-nyc1-01"
    config.vm.box = "ubuntu/eoan64"
    config.vm.network "private_network", type: "dhcp"
    # sync_folder: make sure puTTY Agent is running
    config.vm.synced_folder ".", "/vagrant", type: 'rsync'
    #config.vm.synced_folder "./static", "/var/www/html", type: 'rsync'
    config.vm.provider :digital_ocean do |provider, override|
      config.ssh.private_key_path = '~/.ssh/vagrant.pem'
      #override.ssh.private_key_path = '/path/to/private/key'
      override.vm.box = 'digital_ocean'
      provider.token = Secret.api_key
      provider.image = 'ubuntu-19-10-x64'
      provider.region = 'nyc1'
      provider.size = 's-1vcpu-1gb'
    end
    config.vm.provision :shell, path: "bootstrap.sh"
  end
end