Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-18.04"
    config.vm.box_check_update = true
    config.vm.boot_timeout = 3600
    config.vm.define "jamstack-webserver"
    config.vm.hostname="jamstack-webserver"
    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'

    config.vm.network "public_network", ip: "192.168.1.240"
    config.vm.network "forwarded_port", guest: 22, host: 9922
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "forwarded_port", guest: 443, host: 443

    config.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=775,fmode=764"]
    config.vm.synced_folder "./data_private", "/home/vagrant/data_private", :mount_options => ["dmode=775,fmode=764"]

    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        export DEBIAN_FRONTEND=noninteractive ; apt-get upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --assume-yes
        apt-get install nginx -y
        sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
        apt-get install nodejs
    SHELL

    config.vm.provider "virtualbox" do |vb|
        vb.name = "jamstack-webserver"
        vb.memory = "1024"
        vb.cpus = 6
    end
end