Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-18.04"
    config.vm.box_check_update = true
    config.vm.boot_timeout = 3600
    config.vm.define "jamstack-webserver"
    config.vm.hostname="jamstack-webserver"
    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'

    config.vm.network "public_network"
    config.vm.network "forwarded_port", guest: 22, host: 9922
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "forwarded_port", guest: 443, host: 443

    config.vm.synced_folder ".", "/home/vagrant/hostdata", {
        type: 'smb', mount_options: ['vers=3.0'],
        smb_host: Secret.smb_host,
        smb_username: Secret.smb_user,
        smb_password: Secret.smd_pwd
        }

    config.vm.synced_folder "static", "/var/www/html", {
        type: 'smb', mount_options: ['vers=3.0'],
        smb_host: Secret.smb_host,
        smb_username: Secret.smb_user,
        smb_password: Secret.smd_pwd
        }

    config.vm.provider "hyperv" do |h|
        vmname = "jamstack-webserver"
        maxmemory = "512"
        cpus = 6
        h.enable_virtualization_extensions = true
        h.linked_clone = true
        end
     end