Vagrant.configure("2") do |config|
    config.vm.define "webServer_droplet" do |node|
    node.vm.host_name = "do-nyc1-websrv"
    config.vm.box = "ubuntu/eoan64"
    config.vm.network "private_network", type: "dhcp"
    # sync_folder: make sure puTTY Agent is running
    config.vm.synced_folder ".", "/vagrant", type: 'rsync'
    config.vm.provider :digital_ocean do |provider, override|
      config.ssh.private_key_path = '~/.ssh/vagrant.pem'
      override.vm.box = 'digital_ocean'
      provider.token = Secret.api_key
      provider.image = 'ubuntu-19-10-x64'
      provider.region = 'nyc1'
      #provider.size = '1gb'
      provider.size = 's-1vcpu-1gb'
    end
    config.vm.provision "shell", inline: <<-SHELL
    cat /vagrant/data_private/id_rsa.pub >> ~/.ssh/authorized_keys
    mkdir -p /var/www
    cd /var/www/
    git clone https://github.com/t0m-a/landingPage.git
    git clone https://github.com/t0m-a/wiki.git
    cp -pr /var/www/wiki/htmlv2/* /var/www/wiki
    rm -rf /var/www/wiki/html
    rm -rf /var/www/wiki/htmlv2
    cp -pr /vagrant/data_private/static/* /var/www/landingPage/
    rm -rf /var/www/html
    apt-get update && apt-get install nginx apache2-utils software-properties-common certbot python-certbot-nginx -y
    SHELL
    config.vm.provision :shell, path: "privateconfsprovision.sh"
  end
end