# -*- mode: ruby -*-
# vi: set ft=ruby :

# Ansible Master Server VM for the Cluster
Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-18.04"
    config.vm.box_check_update = true
    config.vm.boot_timeout = 3600
    config.vm.define "ansible-master-cluster"
    config.vm.hostname="ansible-master-cluster"
    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'
    config.vm.provision "file", source: "./data_private/id_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"
    config.vm.provision "file", source: "./data_private/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    config.vm.provision "file", source: "./sshd_config", destination: "/home/vagrant/sshd_config"

    config.vm.network "public_network"
    config.vm.network "forwarded_port", guest: 22, host: 2222

    config.vm.synced_folder ".", "/home/vagrant/hostdata", {
        type: 'smb', mount_options: ['vers=3.0'],
        smb_host: '192.168.1.3',
        smb_username: Secret.client_id,
        smb_password: Secret.api_key
        }

    config.vm.provision :shell, path: "bootstrap-ansible.sh"

    config.vm.provider "hyperv" do |h|
        vmname = "ansible-master-cluster"
        maxmemory = "256"
        cpus = 6
        h.enable_virtualization_extensions = true
        h.linked_clone = true
       end
    end

# Load Balancer VM for the Cluster
Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-18.04"
    config.vm.box_check_update = true
    config.vm.boot_timeout = 3600
    config.vm.define "load-balancer-cluster"
    config.vm.hostname="load-balancer-cluster"
    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'
    config.vm.provision "file", source: "./data_private/id_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"
    config.vm.provision "file", source: "./sshd_config", destination: "/home/vagrant/sshd_config"

    config.vm.network "public_network"
    config.vm.network "forwarded_port", guest: 22, host: 2223
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "forwarded_port", guest: 443, host: 443

    config.vm.synced_folder ".", "/home/vagrant/hostdata", {
        type: 'smb', mount_options: ['vers=3.0'],
        smb_host: '192.168.1.3',
        smb_username: Secret.client_id,
        smb_password: Secret.api_key
        }

    config.vm.provider "hyperv" do |h|
        vmname = "load-balancer-cluster"
        maxmemory = "256"
        cpus = 6
        h.enable_virtualization_extensions = true
        h.linked_clone = true
        end
     end

# Nginx Servers VMs for the Cluster

# MySQL Servers VMs for the Cluster Master (and Slave)