Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.box_check_update = true
  config.vm.boot_timeout = 3600
  config.vm.define "docker-master"
  config.vm.hostname="docker-master.local"
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = true
  config.ssh.forward_agent = true
  config.ssh.private_key_path = ['~/.ssh/vagrant.pem']
  config.vm.provision "file", source: "~/.ssh/vagrant.pem.pub", destination: "/home/vagrant/.ssh/authorized_keys"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision "file", source: "~/.ssh/aws.pub", destination: "/home/vagrant/.ssh/aws.pub"
  config.vm.provision "file", source: "./sshd_config", destination: "/home/vagrant/sshd_config"
  config.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update
  export DEBIAN_FRONTEND=noninteractive ; apt-get upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --assume-yes
  apt-get install docker.io -y
  sudo curl -L https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  sudo chmod +x /usr/local/bin/docker-compose
  curl -L https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-`uname -s`-`uname -m` -o /usr/local/bin/docker-machine
  sudo chmod +x /usr/local/bin/docker-machine
  sudo usermod -aG root vagrant
  sudo usermod -aG docker vagrant
  SHELL

  # Network customization to run on public and bridge networks
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # Create a public network, which generally matched to bridged network.
  # config.vm.network "public_network"
  # config.vm.network "forwarded_port", guest: 22, host: 2222
  config.vm.network "public_network"

  # Folders shares
  config.vm.synced_folder ".", "/vagrant", {
  type: 'smb', mount_options: ['vers=3.0'],
  smb_host: '192.168.1.3',
  smb_username: Secret.client_id,
  smb_password: Secret.api_key
  }

  config.vm.synced_folder "./data_private", "/home/vagrant/data_private", {
  type: 'smb', mount_options: ['vers=3.0'],
  smb_host: '192.168.1.3',
  smb_username: Secret.client_id,
  smb_password: Secret.api_key
  }

  config.vm.provision "shell", inline: <<-SHELL
  cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
  cat /home/vagrant/.ssh/aws.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL
  config.vm.provision "shell", inline: <<-SHELL
  sudo cp /home/vagrant/sshd_config /etc/ssh/ && chmod 761 /etc/ssh/sshd_config
  sudo service sshd restart
  SHELL

  # Provider configuration
  config.vm.provider "hyperv" do |h|
     vmname = "docker-master"
     maxmemory = "1024"
     cpus = 6
     h.enable_virtualization_extensions = true
     h.linked_clone = true
   end
end